name: "Deploy to AKS"
description: "Deploys the app with Helm to AKS"

inputs:
  api-server-url:
    required: true
    description: "The url of the API server for Kubernetes"
  sa-secret-name:
    required: true
    description: "The name of the secret for the service-account"
  sa-secret-token:
    required: true
    description: "The token of the secret for the service-account"
  repo:
    required: false
    description: "The url of the helm repo"
    default: https://gemeente-denhaag.github.io/helm-charts
  chart:
    required: false
    description: "The name of the helm-chart to use"
    default: generic
  release-name:
    required: true
    description: "The name of the release used by Helm"  
  values-files:
    required: false
    description: "The location and name of the values file used for Helm. Multipe files possible: values.yaml,values-test.yaml. Most right takes precendence."
  namespace:
    required: true
    description: "The namespace of the AKS cluster to deploy to"
  full-image-url:
    required: true
    description: "The url of the image to deploy to AKS, ie: 'test.cr.url/repo-name:imagetag'"
  extra-params:
    required: false
    description: "Extra params allows you to set extra parameters for the helm deployment, ie: '--set image.fullImage=cr-url/repo-name:imagetag --set name=my-app'"

runs:
  using: "composite"
  steps:
    - uses: azure/k8s-set-context@v2
      with:
        method: service-account
        k8s-url: '${{ inputs.api-server-url }}'
        k8s-secret: '${{ inputs.sa-secret-name }}'
        token: '${{ inputs.sa-secret-token }}'

    - name: 'Determine values files'
      shell: bash
      id: prep
      run: |
        inputvaluesfiles="${{ inputs.values-files}}"
        for i in ${inputvaluesfiles//,/ }
        do
            valuesfiles+=" -f ${i}"
        done
        echo "values files to use: ${valuesfiles}"
        echo "::set-output name=VALUESFILES::${valuesfiles}"
      
    - name: 'Deploy to AKS'
      shell: bash
      run: >
        helm upgrade --install --wait --atomic
        --repo ${{ inputs.repo }}
        ${{ inputs.release-name }}
        ${{ inputs.chart }}
        ${{ steps.prep.outputs.VALUESFILES }}
        -n ${{ inputs.namespace }}
        --set image.fullImage=${{ inputs.full-image-url }}
        ${{ inputs.extra-params }}